module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond', 
    'Bustling',
    'Calm' ,
    'Charming' ,
    'Cosmopolitan ',
    'Enchanting ',
    'Fascinating',
    'Fresh' ,
    'Homey ',
    'Inspiring' ,
    'Lively ',
    'Peaceful',
    'Picturesque ',
    'Unspoiled' ,
    'Vibrant '
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow',
    'Valley',
    'Grey',
    'Point',
    'Cathaig',
    'Head'
]